### ISSUE TITLE
DIRT handling of paths is suboptimal

### ISSUE THREAD

**Issue by asafg** [Computational-Plant-Science/DIRT#1]
Hi there,
A client dealing with roots asked for my help installing and running DIRT.
I noticed that the code does not handle paths in a proper way.
I would like to contribute my fixes as well as my Vagrantfile for creating a Virtualbox instance capable of running DIRT.
Could you please grant me push permissions on this project?

**Comment by koalaspirit** [comment]
Sure! Thanks for your contribution. I added push permissions for you

**Comment by asafg** [comment]
I pushed my fixed to the master branch.
I will arrange the Vagrant stuff later on and push as well.
